@include('frontend/partials/header')
@include('frontend/partials/navbar')
@include('frontend/partials/breadcrumb')
<main>
  @yield('content')
</main>
@include('frontend/partials/feature')
@include('frontend/partials/flashMessage')
@include('frontend/partials/footer')
